const data = {
  translators: [
    {
      name: 'Joana Madiwo',
      slug: 'joana-madiwo',
      category: 'sign to english',
      image: '/images/translator1.jpg',
      price: 750,
      rating: 4.5,
      numReviews: 10,
      description: 'I will translate, interprate sign language to english',
    },
    {
      name: 'Daren Wallace',
      slug: 'daren-wallace',
      category: 'sign to Swahili',
      image: '/images/translator2.jpg',
      price: 550,
      rating: 4.5,
      numReviews: 10,
      description: 'I will translate, interprate sign language to swahili',
    },
    {
      name: 'Cynthia Omuse',
      slug: 'cynthia-omuse',
      category: 'sign to english',
      image: '/images/translator3.jpg',
      price: 750,
      rating: 3.5,
      numReviews: 10,
      description: 'I will translate, interprate sign language to english',
    },
    {
      name: 'Denvah Wainaina',
      slug: 'denvah-wainaina',
      category: 'sign to Kikuyu',
      image: '/images/translator4.jpg',
      price: 1000,
      rating: 2.5,
      numReviews: 6,
      description: 'I will translate, interprate sign language to kikuyu',
    },
    {
      name: 'Lydia Atieno',
      slug: 'lydia-atieno',
      category: 'sign to swahili',
      image: '/images/translator5.jpg',
      price: 500,
      rating: 4.5,
      numReviews: 10,
      description: 'I will translate, interprate sign language to swahili',
    },
  ],
};
export default data;
